# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, verbose_name='initial_picture'),
        ),
    ]
